# Generated by Django 4.1.7 on 2023-03-05 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('performance_review', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name_plural': 'Employees'},
        ),
        migrations.RemoveField(
            model_name='employee',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='email',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='last_name',
        ),
        migrations.AddField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateTimeField(blank=True, help_text='Date of Birth - Format must be YYYY-MM-DD', null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female')], default='m', max_length=1),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.TextField(blank=True, help_text='Complete address within area/street, city state and country etc.', null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='contact_no',
            field=models.CharField(blank=True, help_text='employee phone or landline number', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='joined_on',
            field=models.DateTimeField(blank=True, help_text='Date of Joining - Format must be YYYY-MM-DD', null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='nic',
            field=models.CharField(blank=True, help_text='National Identification Card or ID card', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='org_id',
            field=models.CharField(blank=True, help_text='Organizational Registration Number or ID', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='rank',
            field=models.CharField(blank=True, choices=[('CEO', 'Chief Executive Officer'), ('DIR', 'Director'), ('MAN', 'Manager'), ('WOR', 'Worker'), ('OTH', 'Other')], help_text='Employee Rank/Post/Destination within organization', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='updated_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
