# Generated by Django 4.1.7 on 2023-03-05 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('performance_review', '0002_alter_employee_options_remove_employee_created_on_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='small description of this task 25-100 characters', max_length=1000)),
                ('is_active', models.BooleanField(default=True, help_text='If you check this it means the task is active and if you disable it it will be removed temporary')),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performance_review.employee')),
            ],
        ),
    ]
